### ISSUE TITLE
28 throws an error if temporary files are found

### ISSUE THREAD

**Issue by gislenius** [28msec/28#65]
28 crashes if temporary files are found, like so:

    [{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"read"},{"response":{"readable":false,"domain":null,"_maxListeners":10,"httpVersion":"1.1","complete":true,"_pendingIndex":0,"url":"","method":null,"statusCode":400,"_consuming":true,"_dumped":false,"httpVersionMajor":1,"httpVersionMinor":1,"upgrade":false,"body":"{ \"request_id\" : \"54f850f754641069a681e896\", \"context\" : \"edinet-dev.28.io\", \"description\" : \"The query path must end with \\\".jq\\\" or \\\".xq\\\".\", \"message\" : \"The ... (truncated)

It would be nice if it could just ignore files with other extensions than .jq and .xq

**Comment by wcandillon** [comment]
Indeed indeed :) Thks for reporting this!
